[package]
name = "bluetui"
version = "0.7.1"
authors = ["Badr Badri <contact@pythops.com>"]
license = "GPL-3.0"
edition = "2024"
description = "TUI for managing bluetooth on Linux"
readme = "Readme.md"
homepage = "https://github.com/pythops/bluetui"
repository = "https://github.com/pythops/bluetui"

[dependencies]
async-channel = "2"
bluer = { version = "0.17", features = ["full"] }
crossterm = { version = "0.29", default-features = false, features = [
    "event-stream",
] }
futures = "0.3"
ratatui = "0.29"
tokio = { version = "1", features = ["full"] }
dirs = "6"
toml = "0.9"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive", "cargo"] }
terminal-light = "1"
tui-input = "0.12"

[profile.release]
strip = true
codegen-units = 1
lto = "fat"

[package.metadata.deb]
maintainer = "Emil Hammarström <emil.a.hammarstrom@gmail.com>"
copyright = "2025, Badr Badri <contact@pythops.com>"
depends = "$auto"           # auto-detects libc, etc.
section = "utils"
priority = "optional"
assets = [
  ["target/release/your-app", "/usr/bin/", "755"],
  # Optional: shell completions, man pages, etc.
  ["completions/your-app.bash", "/usr/share/bash-completion/completions/your-app", "644"],
  ["completions/_your-app", "/usr/share/zsh/vendor-completions/_your-app", "644"],
  ["man/your-app.1", "/usr/share/man/man1/your-app.1", "644"]
]
# Optional systemd service example:
systemd_units = [
  { unit_name = "your-app.service", unit_path = "packaging/systemd/your-app.service" }
]
